### ISSUE TITLE
cross-origin error when website inside an iframe

### ISSUE THREAD

**Issue by d3bgger** [skroutz/analytics.js#44]
Hello,

when a website that uses skroutz analytics is loaded inside an iframe from a different domain, the following error is thrown in console:

`Uncaught DOMException: Blocked a frame with origin "http://local.website.gr" from accessing a cross-origin frame.
    at https://analytics.skroutz.gr/js/payload.2a28b3be.min.js:1:5346
    at https://analytics.skroutz.gr/js/payload.2a28b3be.min.js:2:21298`

**Comment by kosdiamantis** [comment]
Hello @d3bgger,

Thank you for reporting it, I'll try to reproduce it and i will come back with a response/fix.
